<?php
/**
 * Conservative verifier for the current public reader's canonical strings.
 * Never generates a publishedValueHash. Unsupported input fails closed.
 * Hashes continue to be generated by the existing TypeScript reader helper.
 */
function escomi_official_projection_text( $value ) {
    if ( null === $value || is_bool( $value ) || is_array( $value ) ) { return ''; }
    if ( is_int( $value ) && abs( $value ) <= 9007199254740991 ) { $value = (string) $value; }
    if ( ! is_string( $value ) || ! preg_match( '//u', $value ) || ! class_exists( 'Normalizer' ) ) { return false; }
    // Do not approximate the reader's HTML/entity decoder or unusual controls.
    if ( preg_match( '/[<>&\x00-\x08\x0e-\x1f\x7f\x{0080}-\x{009f}]/u', $value ) ) { return false; }
    $value = preg_replace( '/[\p{Z}\x{FEFF}\t\r\n\f\v]+/u', ' ', $value );
    $value = trim( $value );
    $unknown = array( '-', 'ー', '—', 'null', 'undefined', '未確認', '不明', '要確認', '未掲載', '非公開' );
    if ( '' === $value || preg_match( '/^0(?:\.0+)?$/D', $value ) || in_array( strtolower( $value ), $unknown, true ) ) { return ''; }
    $value = Normalizer::normalize( $value, Normalizer::FORM_KC );
    if ( false === $value ) { return false; }
    return trim( preg_replace( '/[\t\f\v ]+/u', ' ', $value ) );
}

function escomi_official_projection_url( $value ) {
    if ( null === $value || false === $value || '' === $value ) { return ''; }
    if ( ! is_string( $value ) ) { return false; }
    $value = trim( $value );
    if ( '' === $value ) { return ''; }
    // A deliberately narrow WHATWG-stable ASCII URL subset. No dot
    // segments, backslashes, unicode, credentials, fragment or port. Query is
    // retained verbatim, matching WHATWG URL serialization for this ASCII subset.
    if ( ! preg_match( '~^(https?)://([a-z0-9](?:[a-z0-9.-]*[a-z0-9])?)(/[a-zA-Z0-9/_\~!$()*+,;=:@.-]*)?(\?[a-zA-Z0-9_%\~!$()*+,;=:@/?&.-]+)?$~D', $value, $matches ) ) { return false; }
    $host = $matches[2];
    if ( false === strpos( $host, '.' ) || filter_var( $host, FILTER_VALIDATE_IP ) || preg_match( '/(?:^|\.)(?:localhost|local|internal)$/D', $host ) ) { return false; }
    // WHATWG IPv4 accepts integer, abbreviated and hexadecimal hosts.
    if ( preg_match( '/(?:^|\.)(?:[0-9]+|0x[0-9a-f]+)$/iD', $host ) ) { return false; }
    $path = isset( $matches[3] ) && '' !== $matches[3] ? $matches[3] : '/';
    if ( preg_match( '~(?:^|/)\.{1,2}(?:/|$)~', $path ) ) { return false; }
    if (preg_match('/%(?:0[0-9a-f]|1[0-9a-f]|7f)/i',$value)) { return false; }
    return $matches[1] . '://' . $host . $path . ($matches[4] ?? '');
}

function escomi_official_verify_projection( $category, $acf, $canonical ) {
    if ( ! is_array( $acf ) || ! is_string( $canonical ) || ! class_exists( 'Normalizer' ) ) { return false; }
    $get = static function ( $key ) use ( $acf ) { return array_key_exists( $key, $acf ) ? $acf[$key] : null; };
    if ( 'price' === $category ) {
        $projected=array();
        foreach (array(50,60,70,80,90,120,150) as $duration) {
            $raw=$get('price_'.$duration);
            if ($raw===null || $raw==='' || $raw===false || $raw==='0' || $raw===0) { continue; }
            // Existing values remain untouched; unsupported legacy forms fail closed.
            if (is_int($raw)) { $raw=(string)$raw; }
            if (!is_string($raw) || !preg_match('/^[1-9][0-9]{0,6}$/D',$raw)) { return false; }
            $projected[]=array('durationMinutes'=>$duration,'priceYen'=>(int)$raw);
        }
    } elseif ( 'hours' === $category ) {
        $projected = escomi_official_projection_text( $get( 'shop_hours' ) );
        if ( false === $projected ) { return false; }
    } elseif ( 'access' === $category ) {
        $projected = array();
        foreach ( array( 'shop_station', 'nearest_station', 'station' ) as $key ) {
            $text = escomi_official_projection_text( $get( $key ) );
            if ( false === $text ) { return false; }
            if ( '' !== $text ) { $projected[] = $text; break; }
        }
        $address = escomi_official_projection_text( $get( 'shop_address' ) );
        if ( false === $address ) { return false; }
        if ( '' !== $address ) { $projected[] = $address; }
    } elseif ( 'official' === $category ) {
        $projected = escomi_official_projection_url( $get( 'official_url' ) );
        if ( false === $projected ) { return false; }
    } elseif ( 'booking' === $category ) {
        $projected = array();
        foreach ( array( 'shop_booking_url', 'booking_url', 'reservation_url', 'shop_reservation_url' ) as $key ) {
            $url = escomi_official_projection_url( $get( $key ) );
            if ( false === $url ) { return false; }
            if ( '' !== $url ) { $projected[] = array( 'kind' => 'reservation', 'href' => $url ); break; }
        }
        $line = escomi_official_projection_url( $get( 'shop_line' ) );
        if ( false === $line ) { return false; }
        if ( '' !== $line ) { $projected[] = array( 'kind' => 'line', 'href' => $line ); }
        $phone = $get( 'shop_tel' );
        if ( null !== $phone && ! is_string( $phone ) ) { return false; }
        $digits = preg_replace( '/[^0-9]/', '', $phone ?? '' );
        if ( '' !== $digits ) { $projected[] = array( 'kind' => 'tel', 'href' => 'tel:' . $digits ); }
        usort( $projected, static function ( $a, $b ) { return strcmp( $a['kind'], $b['kind'] ); } );
    } else {
        // Images remain outside the bounded dedicated writer.
        return false;
    }
    $encoded = json_encode( $projected, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_LINE_TERMINATORS );
    return is_string( $encoded ) && $encoded === $canonical;
}
